version: '3.8'

services:
  forensic-analyzer:
    build: .
    container_name: forensic-analyzer
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
    tty: true
    stdin_open: true 
