version: '3.8'

services:
  forensic-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forensic-analyzer
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    tty: true
    stdin_open: true
    restart: unless-stopped 